# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Screenipy Test - New Features

on:
  push:
    branches: [ new-features ]
  pull_request:
    branches: [ new-features ]

jobs:

  # Test the source-code
  Test-Source:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4

    - name: Install dependencies for TA-Lib
      run: |
        echo "[+] Github Actions -> Install dependencies for TA-Lib"
        cd .github/dependencies/
        pwd
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install

    - name: Install dependencies using pip
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run a Test with pytest
      run: |
        cd test/
        pytest -v

  # Job to create PR
  Create-Pull-Request:

    runs-on: ubuntu-18.04
    needs: [Test-Source]

    steps:
    - name: Checkout Repo before PR
      uses: actions/checkout@v2

    - name: Create Pull Request (new-features -> main)
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Screenipy Test - Passed. PR created.
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: new-features
        delete-branch: false
        title: '[Screenipy Test] New Feature - Test Passed.'
        body: |
          **Changelog:**
          To be added here by other GitHub action...
        draft: true
          


    